### ISSUE TITLE
📊 Implement Comprehensive Monitoring & Observability Stack

### ISSUE THREAD

**Issue by joelfuller2016** [joelfuller2016/n8n-job-automation-system#12]
## 📊 Description

Create a comprehensive monitoring setup using Prometheus, Grafana, and associated tools to provide real-time visibility into the job automation system's performance, health, and business metrics.

## 🎯 Acceptance Criteria

- [ ] Prometheus collecting metrics from all services
- [ ] Grafana dashboards showing key business and technical metrics
- [ ] Alerting rules for critical system failures
- [ ] Service health monitoring and uptime tracking
- [ ] Job automation specific metrics (success rates, API costs, etc.)
- [ ] Documentation for monitoring setup and usage

### Monitoring Stack Components:
1. **Prometheus** - Metrics collection and storage
2. **Grafana** - Dashboard visualization and alerting
3. **AlertManager** - Alert routing and management
4. **Node Exporter** - System metrics collection
5. **cAdvisor** - Container metrics collection
6. **Uptime Kuma** - Service uptime monitoring

### Key Metrics to Track:
- **System Metrics**: CPU, memory, disk usage, network I/O
- **Application Metrics**: Job success rates, response times, error rates
- **Business Metrics**: Applications sent, responses received, cost per application
- **API Metrics**: OpenAI API usage, rate limits, costs
- **Database Metrics**: Query performance, connection pools, storage usage

### Grafana Dashboards:
1. **System Overview** - Infrastructure health and performance
2. **Application Performance** - Job automation specific metrics
3. **Business Intelligence** - Success rates, costs, ROI analysis
4. **Security Monitoring** - Failed logins, unusual activity
5. **API Usage** - Third-party service consumption and costs

## 📁 Files to Create

- `monitoring/prometheus/prometheus.yml` - Prometheus configuration
- `monitoring/grafana/dashboards/` - Pre-built dashboard definitions
- `monitoring/grafana/datasources/` - Data source configurations
- `monitoring/alertmanager/alertmanager.yml` - Alert routing rules
- `monitoring/alerts/` - Alert rule definitions
- `docs/MONITORING.md` - Setup and usage documentation

### Prometheus Job Configuration:
```yaml
scrape_configs:
  - job_name: 'n8n'
    static_configs:
      - targets: ['n8n:5678']
    metrics_path: '/metrics'
    
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
    
  - job_name: 'redis' 
    static_configs:
      - targets: ['redis_exporter:9121']
```

### Alert Rules Example:
```yaml
- alert: N8NWorkflowFailure
  expr: increase(n8n_workflow_executions_failed_total[5m]) > 0
  for: 1m
  labels:
    severity: warning
  annotations:
    summary: "n8n workflow execution failed"
    
- alert: HighAPICosse
  expr: sum(rate(openai_api_cost[1h])) > 10
  for: 5m
  labels:
    severity: warning
  annotations:
    summary: "OpenAI API costs are high"
```

## 🧪 Testing Requirements

- [ ] All monitoring services start correctly
- [ ] Metrics are being collected and stored
- [ ] Dashboards display data correctly
- [ ] Alerts fire when conditions are met
- [ ] Alert notifications reach configured endpoints
- [ ] Performance impact on main services is minimal

## 📊 Success Metrics

- **Visibility**: 100% of critical services monitored
- **Alerting**: <5 minute detection time for critical issues
- **Performance**: <1% overhead on main application
- **Usability**: Non-technical users can read main dashboards
- **Reliability**: 99.9% monitoring system uptime

## 🔗 Related Issues

- Depends on: Docker Infrastructure (#6)
- Enables: Performance Optimization (#TBD)
- Supports: Production Deployment (#TBD)

## 🏷️ Labels

`monitoring`, `observability`, `grafana`, `prometheus`, `infrastructure`, `phase-1`, `high-priority`

---

**💡 Tips for Contributors:**
- Start with basic system metrics before adding custom application metrics
- Use existing Grafana dashboard templates as starting points
- Test alert rules thoroughly to avoid false positives
- Document metric meanings for non-technical users
- Consider using Grafana's provisioning for reproducible setups
